### ISSUE TITLE
Source code and license

### ISSUE THREAD

**Issue by aramk** [mortonfox/YouTim#1]
This library looked quite useful, but it has two drawbacks I'd like to mention:
- The source code is embedded inside the gh-pages branch. Ideally it should reside in the master branch and the github pages branch could use a copy as necessary.
- The license is GPLv3, which restricts any code using it to also be under GPLv3. Therefore, a library using a more lenient non-copyleft license like MIT, BSD or Apache2 cannot use this library. Would you consider changing it to one of these?

**Comment by aramk** [comment]
I went with a different implementation and wrapped it here: https://github.com/urbanetic/utm-converter

**Comment by mortonfox** [comment]
I added a copy of utmconv.js to the master branch and switched the library to LGPL.

**Comment by aramk** [comment]
Thanks!
